services:
    govwiki.user_bundle.listener.registration:
        class: GovWiki\UserBundle\EventListener\RegistrationListener
        arguments:
            - @session
            - @security.token_storage
        tags:
            - { name: kernel.event_subscriber }

    govwiki.user_bundle.handler.login:
        class: GovWiki\UserBundle\Security\LoginSuccessHandler
        arguments:
            - @router
            - @doctrine.orm.default_entity_manager

    govwiki.user_bundle.redirection.logout:
        class: GovWiki\UserBundle\Security\LogoutSuccessHandler

    govwiki.user_bundle.redirection.access_denied:
        class: GovWiki\UserBundle\Security\AccessDeniedHandler
        arguments: [@session]

    govwiki.user_bundle.chat_message:
        class: GovWiki\UserBundle\Service\ChatMessage
        arguments: ["@doctrine.orm.entity_manager", "@templating"]

    govwiki.user.form.registration:
        class: GovWiki\UserBundle\Form\RegistrationForm
        tags:
            - { name: form.type, alias: app_user_registration }