services:
    govwiki_generator.worker.government_generator:
        class: 'GovWiki\GeneratorBundle\Worker\GovernmentGeneratorWorker'
        arguments: [ '@monolog.logger.generator' ]
        calls:
            - ['setContainer', [ '@service_container' ]]

    govwiki_generator.worker.elected_generator:
        class: 'GovWiki\GeneratorBundle\Worker\ElectedGeneratorWorker'
        arguments: [ '@monolog.logger.generator' ]
        calls:
            - ['setContainer', [ '@service_container' ]]

    govwiki_generator.worker.california_parser:
        class: 'GovWiki\GeneratorBundle\Worker\CaliforniaWorker'
        arguments: [ '@monolog.logger.parser' ]
        calls:
            - ['setContainer', [ '@service_container' ]]

    govwiki_generator.pid_pool_factory:
        class: GovWiki\GeneratorBundle\Service\PidPoolFactory
        arguments: [ '%kernel.cache_dir%' ]

    twig.extension.assets:
        class: 'GovWiki\GeneratorBundle\Twig\AssetExtension'
        arguments:
            - '@assets.packages'
            - '@request_stack'
            - '%kernel.root_dir%/../web'
            - '@twig.extension.httpfoundation'
            - '@govwiki_environment.storage'
        public: false
