localization:
    resource: "@GovWikiMobileBundle/Controller/LocalizationController.php"
    type:     govwiki

elected:
    resource: "@GovWikiMobileBundle/Controller/ElectedController.php"
    type:     govwiki

government:
    resource: "@GovWikiMobileBundle/Controller/GovernmentController.php"
    type:     govwiki

main:
    resource: "@GovWikiMobileBundle/Controller/MainController.php"
    type:     govwiki
    prefix:   /

robots:
    resource: "@GovWikiMobileBundle/Controller/RobotsController.php"
    type:     annotation
