services:
    govwiki.mobile_bundle.advertising:
        class: GovWiki\MobileBundle\Service\GetAdvertising
        arguments: ["@doctrine", "@templating"]

    govwiki.mobile_bundle.environment_content:
        class: GovWiki\MobileBundle\Service\EnvironmentContent
        arguments: ["@doctrine", "@templating"]