services:
    govwiki.frontend_bundle.twig_extension:
        class: GovWiki\MobileBundle\Twig\Extension
        arguments:
            - @jms_serializer
            - %determinator.name%
            - @service_container
            - @translator
        tags:
            - { name: twig.extension }

    govwiki.frontend_bundle.advertising:
        class: GovWiki\MobileBundle\Service\GetAdvertising
        arguments: ["@doctrine", "@templating"]

    govwiki.frontend_bundle.environment_content:
        class: GovWiki\MobileBundle\Service\EnvironmentContent
        arguments: ["@doctrine", "@templating"]

    govwiki.forntend_bundle.listener.defaul_locale:
        class: GovWiki\MobileBundle\EventListener\DefaultLocaleListener
        arguments: [@service_container]
        tags:
            -
                name: kernel.event_listener
                event: kernel.request
                priority: 15