
elected:
    resource: "@GovWikiFrontendBundle/Controller/ElectedController.php"
    type:     annotation

government:
    resource: "@GovWikiFrontendBundle/Controller/GovernmentController.php"
    type:     annotation

main:
    resource: "@GovWikiFrontendBundle/Controller/MainController.php"
    type:     annotation
    prefix:   /
