editrequest:
    resource: "@GovWikiFrontendBundle/Controller/GovernmentController.php"
    type:     annotation
    prefix:   /

main:
    resource: "@GovWikiFrontendBundle/Controller/MainController.php"
    type:     annotation
    prefix:   /
