localization:
    resource: "@GovWikiFrontendBundle/Controller/LocalizationController.php"
    type:     annotation

government:
    resource: "@GovWikiFrontendBundle/Controller/GovernmentController.php"
    type:     annotation

elected:
    resource: "@GovWikiFrontendBundle/Controller/ElectedController.php"
    type:     annotation

main:
    resource: "@GovWikiFrontendBundle/Controller/MainController.php"
    type:     annotation
    prefix:   /

robots:
    resource: "@GovWikiFrontendBundle/Controller/RobotsController.php"
    type:     annotation
