services:
    govwiki.frontend_bundle.twig_extension:
        class: GovWiki\FrontendBundle\Twig\Extension
        arguments:
            - @govwiki_api.manager.environment
            - @jms_serializer
            - %determinator.name%
            - @service_container
            - @translator
        tags:
            - { name: twig.extension }

    govwiki.frontend_bundle.adverting:
        class: GovWiki\FrontendBundle\Service\GetAdverting
        arguments: ["@doctrine", "@templating"]