services:
    govwiki.frontend_bundle.twig_extension:
        class: GovWiki\FrontendBundle\Twig\Extension
        tags:
            - { name: twig.extension }

    govwiki.frontend_bundle.advertising:
        class: GovWiki\FrontendBundle\Service\GetAdvertising
        arguments:
            - @doctrine.orm.default_entity_manager
            - @templating

    govwiki.frontend_bundle.environment_content:
        class: GovWiki\FrontendBundle\Service\EnvironmentContent
        arguments: ["@doctrine", "@templating"]