government:
    resource: "@GovWikiApiBundle/Controller/V1/GovernmentController.php"
    type:     annotation

elected-official:
    resource: "@GovWikiApiBundle/Controller/V1/ElectedOfficialController.php"
    type:     annotation
    prefix:   elected-official

create-request:
    resource: "@GovWikiApiBundle/Controller/V1/CreateRequestController.php"
    type:     annotation

edit-request:
    resource: "@GovWikiApiBundle/Controller/V1/EditRequestController.php"
    type:     annotation

url:
    resource: "@GovWikiApiBundle/Controller/V1/UrlController.php"
    type:     annotation

comparison:
    resource: "@GovWikiApiBundle/Controller/V1/ComparisonController.php"
    type:     annotation

twilio_sms:
    resource: "@GovWikiApiBundle/Controller/V1/TwilioSmsController.php"
    type:     annotation