imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_mobile.yml"
        strict_requirements: ~
    profiler: { only_exceptions: false }

# Assetic Configuration
assetic:
    bundles:
        - 'GovWikiMobileBundle'
        - 'GovWikiCommentBundle'

web_profiler:
    toolbar: true
    intercept_redirects: false

mobile_detect:
    redirect:
        mobile:
            is_enabled: false
        tablet: ~
        full:
            is_enabled: true
            host: http://some.host
    switch_device_view: ~
    request_response_listener_class: GovWiki\MobileDetectBundle\EventListener\GovWikiRequestResponseListener