gov_wiki_api:
    resource: "@GovWikiApiBundle/Resources/config/routing.yml"
    prefix:   /api

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

gov_wiki_user:
    resource: "@GovWikiUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_oauth_server_token:
    path: /token
    defaults: { _controller: fos_oauth_server.controller.token:tokenAction }

fos_oauth_server_authorize:
    path: /authorize
    defaults: { _controller: FOSOAuthServerBundle:Authorize:authorize }

logout:
    path: /api/logout