gov_wiki_api:
    resource: "@GovWikiApiBundle/Resources/config/routing.yml"
    prefix:   /api

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

gov_wiki_user:
    resource: "@GovWikiUserBundle/Resources/config/routing.yml"
    prefix:   /

