_main:
    resource: routing.yml

govwiki_frontend:
    resource: "@GovWikiFrontendBundle/Resources/config/routing.yml"
    prefix: /

link:
  resource: '@GovWikiEnvironmentBundle/Controller/LinkController.php'
  type: annotation