gov_wiki_admin:
    resource: "@GovWikiAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

gov_wiki_api:
    resource: "@GovWikiApiBundle/Resources/config/routing.yml"
    prefix:   /api

