gov_wiki_api:
    resource: "@GovWikiApiBundle/Resources/config/routing.yml"
    prefix:   /api

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix:   /admin

#gov_wiki_user:
#    resource: "@GovWikiUserBundle/Resources/config/routing.yml"
#    prefix:   /admin

fos_oauth_server_token:
    path: /token
    defaults: { _controller: fos_oauth_server.controller.token:tokenAction }

fos_oauth_server_authorize:
    path: /authorize
    defaults: { _controller: FOSOAuthServerBundle:Authorize:authorize }

api_logout:
    path: /api/logout

gov_wiki_admin:
    resource: "@GovWikiAdminBundle/Resources/config/routing.yml"
    prefix:   /admin