imports:
  - { resource: '@GovWikiFileLibraryBundle/Resources/config/services.yml' }

services:
    fos_user.doctrine_registry:
        alias: doctrine

    app.form.registration:
        class: GovWiki\UserBundle\Form\RegistrationForm
        arguments:
          - '@govwiki_environment.storage'
        tags:
            - { name: form.type, alias: app_user_registration }