services:
    #
    # Parent for all admin entity managers.
    #
    govwiki_admin.entity_manager.abstract:
        class: GovWiki\AdminBundle\Manager\AbstractAdminEntityManager
        arguments:
            - @doctrine.orm.default_entity_manager
            - @govwiki_environment.storage
        abstract: true

    #
    # Format admin entity manager.
    #
    govwiki_admin.entity_manager.format:
        class: GovWiki\AdminBundle\Manager\Entity\AdminFormatManager
        parent: govwiki_admin.entity_manager.abstract

    #
    # Tab admin entity manager.
    #
    govwiki_admin.entity_manager.tab:
        class: GovWiki\AdminBundle\Manager\Entity\AdminTabManager
        parent: govwiki_admin.entity_manager.abstract

    #
    # Category admin entity manager.
    #
    govwiki_admin.entity_manager.category:
        class: GovWiki\AdminBundle\Manager\Entity\AdminCategoryManager
        parent: govwiki_admin.entity_manager.abstract

    #
    # Locale admin entity manager.
    #
    govwiki_admin.entity_manager.locale:
        class: GovWiki\AdminBundle\Manager\Entity\AdminLocaleManager
        parent: govwiki_admin.entity_manager.abstract

    #
    # Translation admin entity manager.
    #
    govwiki_admin.entity_manager.translation:
        class: GovWiki\AdminBundle\Manager\Entity\AdminTranslationManager
        parent: govwiki_admin.entity_manager.abstract

    #
    # FinData admin entity manager.
    #
    govwiki_admin.entity_manager.fin_data:
        class: GovWiki\AdminBundle\Manager\Entity\AdminFinDataManager
        parent: govwiki_admin.entity_manager.abstract

    #
    # VoteComment admin entity manager.
    #
    govwiki_admin.entity_manager.vote_comment:
        class: GovWiki\AdminBundle\Manager\Entity\AdminCommentManager
        parent: govwiki_admin.entity_manager.abstract