main:
    resource: "@GovWikiAdminBundle/Controller/MainController.php"
    type:     annotation

government:
    resource: "@GovWikiAdminBundle/Controller/GovernmentController.php"
    type:     annotation

electedofficial:
    resource: "@GovWikiAdminBundle/Controller/ElectedOfficialController.php"
    type:     annotation

legislation:
    resource: "@GovWikiAdminBundle/Controller/LegislationController.php"
    type:     annotation

electedofficialvote:
    resource: "@GovWikiAdminBundle/Controller/ElectedOfficialVoteController.php"
    type:     annotation

contribution:
    resource: "@GovWikiAdminBundle/Controller/ContributionController.php"
    type:     annotation

endorsement:
    resource: "@GovWikiAdminBundle/Controller/EndorsementController.php"
    type:     annotation

publicstatement:
    resource: "@GovWikiAdminBundle/Controller/PublicStatementController.php"
    type:     annotation

createrequest:
    resource: "@GovWikiAdminBundle/Controller/CreateRequestController.php"
    type:     annotation

editrequest:
    resource: "@GovWikiAdminBundle/Controller/EditRequestController.php"
    type:     annotation

user:
    resource: "@GovWikiAdminBundle/Controller/UserController.php"
    type:     annotation

map:
    resource: "@GovWikiAdminBundle/Controller/MapController.php"
    type:     annotation

format:
    resource: "@GovWikiAdminBundle/Controller/FormatController.php"
    type:     annotation

tab:
    resource: "@GovWikiAdminBundle/Controller/TabController.php"
    type:     annotation

category:
    resource: "@GovWikiAdminBundle/Controller/CategoryController.php"
    type:     annotation

wizard:
    resource: @GovWikiAdminBundle/Controller/WizardController.php
    type:     annotation

fin_data:
    resource: @GovWikiAdminBundle/Controller/FinDataController.php
    type:     annotation