main:
    resource: "@GovWikiAdminBundle/Controller/MainController.php"
    type:     annotation
    prefix:   /

government:
    resource: "@GovWikiAdminBundle/Controller/GovernmentController.php"
    type:     annotation
    prefix:   /government

electedofficial:
    resource: "@GovWikiAdminBundle/Controller/ElectedOfficialController.php"
    type:     annotation
    prefix:   /electedofficial
