wizard:
    resource: @GovWikiAdminBundle/Controller/WizardController.php
    type:     annotation

main:
    resource: "@GovWikiAdminBundle/Controller/MainController.php"
    type:     annotation

environment:
    resource: "@GovWikiAdminBundle/Controller/EnvironmentController.php"
    type:     annotation

government:
    resource: "@GovWikiAdminBundle/Controller/GovernmentController.php"
    type:     annotation

government_data:
    resource: "@GovWikiAdminBundle/Controller/GovernmentDataController.php"
    type:     annotation

electedofficial:
    resource: "@GovWikiAdminBundle/Controller/ElectedOfficialController.php"
    type:     annotation

legislation:
    resource: "@GovWikiAdminBundle/Controller/LegislationController.php"
    type:     annotation

contribution:
    resource: "@GovWikiAdminBundle/Controller/ContributionController.php"
    type:     annotation

endorsement:
    resource: "@GovWikiAdminBundle/Controller/EndorsementController.php"
    type:     annotation

publicstatement:
    resource: "@GovWikiAdminBundle/Controller/PublicStatementController.php"
    type:     annotation

createrequest:
    resource: "@GovWikiAdminBundle/Controller/CreateRequestController.php"
    type:     annotation

editrequest:
    resource: "@GovWikiAdminBundle/Controller/EditRequestController.php"
    type:     annotation

user:
    resource: "@GovWikiAdminBundle/Controller/UserController.php"
    type:     annotation

admin_user:
    resource: "@GovWikiAdminBundle/Controller/AdminUserController.php"
    type:     annotation

field:
    resource: "@GovWikiAdminBundle/Controller/FieldController.php"
    type:     annotation

tab:
    resource: "@GovWikiAdminBundle/Controller/TabController.php"
    type:     annotation

category:
    resource: "@GovWikiAdminBundle/Controller/CategoryController.php"
    type:     annotation

fin_data:
    resource: @GovWikiAdminBundle/Controller/FinDataController.php
    type:     annotation

legend:
    resource: "@GovWikiAdminBundle/Controller/LegendController.php"
    type:     annotation

shape:
    resource: "@GovWikiAdminBundle/Controller/ShapeController.php"
    type:      annotation

advertising:
    resource: "@GovWikiAdminBundle/Controller/AdvertisingController.php"
    type:     annotation

locale:
    resource: @GovWikiAdminBundle/Controller/LocalizationController.php
    type:     annotation

global_locale:
    resource: @GovWikiAdminBundle/Controller/GlobalLocalizationController.php
    type:     annotation

subscriber:
    resource: @GovWikiAdminBundle/Controller/SubscribeController.php
    type:     annotation

styles:
    resource: @GovWikiAdminBundle/Controller/StyleController.php
    type:     annotation

document:
    resource: @GovWikiAdminBundle/Controller/DocumentController.php
    type:     annotation

comment:
    resource: @GovWikiAdminBundle/Controller/CommentController.php
    type:     annotation