services:
    govwiki_admin.twig.extension:
        class: GovWiki\AdminBundle\Twig\TwigExtensions
        arguments: [ @govwiki_environment.storage ]
        tags:
            - { name: twig.extension }

    govwiki_admin.manager.transformer:
        class: GovWiki\AdminBundle\Transformer\Service\TransformerManager
        arguments: [@service_container]

    govwiki_admin.manager.government_table:
        class: GovWiki\AdminBundle\Manager\GovernmentTableManager
        arguments: [@doctrine.orm.default_entity_manager]

    govwiki_admin.manager.environment:
        class: GovWiki\AdminBundle\Manager\AdminEnvironmentManager
        arguments:
            - @doctrine.orm.default_entity_manager
            - @govwiki_admin.manager.government_table
            - @carto_db.api

    govwiki_admin.manager.style:
        class: GovWiki\AdminBundle\Manager\AdminStyleManager
        arguments: [ @doctrine.orm.default_entity_manager ]

    govwiki_admin.listener.government_sync:
        class: GovWiki\AdminBundle\Listener\GovernmentUpdateListener
        arguments: [@carto_db.api]
        tags:
            -
                name: kernel.event_listener
                event: gowviki.event.government.add
                method: onGovernmentAdd
            -
                name: kernel.event_listener
                event: govwiki.event.government.update
                method:

    goviki_admin.param_converter.environment:
        class: GovWiki\AdminBundle\Request\ParamConverter\EnvironmentParamConverter
        arguments: [ @doctrine.orm.default_entity_manager ]
        tags:
            - { name: request.param_converter, converter: environment_converter }

    govwiki_admin.listener.wizard:
        class: GovWiki\AdminBundle\Listener\WizardStepListener
        arguments: [@session]
        tags:
            - { name: kernel.event_listener, event: kernel.controller }

    govwiki_admin.sitemap.generator.txt:
        class: GovWiki\AdminBundle\Services\TxtSitemapGenerator
        arguments:
            - @doctrine.orm.default_entity_manager
            - @router
            - %determinator.name%
            - %kernel.root_dir%/../web/

    govwiki_admin.manager.shape:
        class: GovWiki\AdminBundle\Services\ShapeManager
        arguments:
            - @doctrine.orm.default_entity_manager
            - %kernel.root_dir%/../web/
            - img/upload/shape/

    govwiki_admin.form.type.delay:
        class: GovWiki\AdminBundle\Form\Type\DelayType
        tags:
            - { name: form.type, alias: delay }