services:
    govwiki_admin.command.script_run:
        class: 'GovWiki\AdminBundle\Command\RunScriptCommand'
        arguments:
            - '@govwiki_admin.repository.script_queued_item'
        tags:
            - { name: console.command }

    govwiki_admin.twig.extension:
        class: GovWiki\AdminBundle\Twig\TwigExtensions
        arguments: [ @govwiki_environment.storage ]
        tags:
            - { name: twig.extension }

    govwiki_admin.manager.transformer:
        class: GovWiki\AdminBundle\Transformer\Service\TransformerManager
        arguments: [@service_container]

    govwiki_admin.listener.environment:
        class: GovWiki\AdminBundle\Listener\EnvironmentListener
        arguments:
            - @doctrine.orm.default_entity_manager
            - @govwiki_environment.storage
        tags:
            - { name: kernel.event_listener, event: kernel.controller}

    goviki_admin.param_converter.environment:
        class: GovWiki\AdminBundle\Request\ParamConverter\EnvironmentParamConverter
        arguments: [ @doctrine.orm.default_entity_manager ]
        tags:
            - { name: request.param_converter, converter: environment_converter }

    govwiki_admin.listener.wizard:
        class: GovWiki\AdminBundle\Listener\WizardStepListener
        arguments: [@session]
        tags:
            - { name: kernel.event_listener, event: kernel.controller }

    govwiki_admin.sitemap.generator.txt:
        class: GovWiki\AdminBundle\Services\TxtSitemapGenerator
        arguments:
            - @doctrine.orm.default_entity_manager
            - @router
            - %determinator.name%
            - %kernel.root_dir%/../web/

    govwiki_admin.manager.shape:
        class: GovWiki\AdminBundle\Services\ShapeManager
        arguments:
            - @doctrine.orm.default_entity_manager
            - %kernel.root_dir%/../web/
            - upload/shape/

    govwiki_admin.repository.script_queued_item:
        class: 'GovWiki\AdminBundle\Entity\Repository\ScriptQueueItemRepository'
        factory: [ '@doctrine.orm.default_entity_manager', 'getRepository' ]
        arguments:
          - 'GovWiki\AdminBundle\Entity\ScriptQueueItem'

    govwiki_admin.form.type.delay:
        class: GovWiki\AdminBundle\Form\Type\DelayType
        tags:
            - { name: form.type, alias: delay }