services:
    govwiki_admin.twig.extension:
        class: GovWiki\AdminBundle\Twig\TwigExtensions
        arguments: [@govwiki_admin.manager.environment]
        tags:
            - { name: twig.extension }

    govwiki_admin.manager.transformer:
        class: GovWiki\AdminBundle\Transformer\Service\TransformerManager
        arguments: [@service_container]

    govwiki_admin.manager.government_table:
        class: GovWiki\AdminBundle\Manager\GovernmentTableManager
        arguments: [@doctrine.orm.default_entity_manager]

    govwiki_admin.manager.environment:
        class: GovWiki\AdminBundle\Manager\AdminEnvironmentManager
        arguments:
            - @doctrine.orm.default_entity_manager
            - @security.token_storage
            - @session
            - @govwiki_admin.manager.government_table

    govwiki_admin.manager.style:
        class: GovWiki\AdminBundle\Manager\AdminStyleManager
        arguments:
            - @form.factory
            - @govwiki_admin.manager.environment
            - %kernel.root_dir%/../web/img/upload

#    govwiki_admin.listener.government_sync:
#        class: GovWiki\AdminBundle\Listener\SyncGovernmentWithCartoDb
#        arguments: [@carto_db.api]
#        tags:
#            - { name: doctrine.event_subscriber }

#    govwiki_admin.listener.government_table_upadte:
#        class: GovWiki\AdminBundle\Listener\UpdateGovernmentTable
#        arguments: [@service_container]
#        tags:
#            - { name: doctrine.event_subscriber }

    govwiki_admin.listener.wizard:
        class: GovWiki\AdminBundle\Listener\WizardStepListener
        arguments: [@session]
        tags:
            - { name: kernel.event_listener, event: kernel.controller }

    govwiki_admin.sitemap.generator.txt:
        class: GovWiki\AdminBundle\Services\TxtSitemapGenerator
        arguments:
            - @doctrine.orm.default_entity_manager
            - @router
            - %determinator.name%
            - %kernel.root_dir%/../web/

    govwiki_admin.manager.shape:
        class: GovWiki\AdminBundle\Services\ShapeManager
        arguments:
            - @doctrine.orm.default_entity_manager
            - %kernel.root_dir%/../web/
            - img/uploads/shape/