services:
    govwiki_api.cors.listener:
        class: GovWiki\ApiBundle\Listener\CorsListener
        tags:
            - { name: kernel.event_listener, event: kernel.request,  method: onKernelRequest,  priority: 100}
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: -100}