services:

    govwiki_db.form.type.environment:
        class: GovWiki\DbBundle\Form\EnvironmentType
        arguments: [ %kernel.root_dir%/../web]
        tags:
            - { name: form.type, alias: environment }

    govwiki_db.form.type.alt_type:
        class: GovWiki\DbBundle\Form\Type\AltTypeType
        arguments:
            - @govwiki_environment.storage
            - @govwiki_environment.manager.government
        tags:
            - { name: form.type, alias: alt_type }

    govwiki_db.form.type.elected_official:
        class: GovWiki\DbBundle\Form\ElectedOfficialType
        arguments: [ @doctrine.orm.default_entity_manager ]
        tags:
            - { name: form.type, alias: govwiki_dbbundle_electedofficial }

    govwiki_db.form.type.color:
        class: GovWiki\DbBundle\Form\Type\ColorType
        tags:
            - { name: form.type, alias: color }

    govwiki_db.form.government:
        class: GovWiki\DbBundle\Form\GovernmentType
        arguments:
            - %kernel.root_dir%/../web
            - @govwiki_environment.storage
            - @govwiki_environment.manager.government
        tags:
            - { name: form.type, alias: government }

    govwiki_db.form.shape:
        class: GovWiki\DbBundle\Form\Type\ShapeType
        arguments:
            - @govwiki_admin.manager.shape
            - @doctrine.orm.default_entity_manager
        tags:
            - { name: form.type, alias: shape }

    govwiki_db.form.fin_data:
        class: GovWiki\DbBundle\Form\FinDataType
        arguments: [ @govwiki_environment.storage ]
        tags:
            - { name: form.type, alias: fin_data }

    govwiki_db.form.ext_government:
        class: GovWiki\DbBundle\Form\ExtGovernmentType
        arguments:
            - @govwiki_environment.storage
            - @govwiki_environment.manager.format
        tags:
            - { name: form.type, alias: ext_government }

    govwiki_db.form.new_ext_government:
        class: GovWiki\DbBundle\Form\NewExtGovernmentType
        arguments:
            - @govwiki_environment.storage
            - @govwiki_environment.manager.format
            - @govwiki_environment.manager.government
        tags:
            - { name: form.type, alias: new_ext_government }

    govwiki_db.form.document:
        class: GovWiki\DbBundle\Form\DocumentType
        arguments:
            - %kernel.root_dir%/../web/
            - 'documents'
        tags:
            - { name: form.type, alias: document }

    govwiki_db.form.legislation:
        class: GovWiki\DbBundle\Form\LegislationType
        arguments: [ @govwiki_environment.storage ]
        tags:
            - { name: form.type, alias: govwiki_dbbundle_legislation }