services:
    govwiki_db.service.max_ranks_computer:
        class: GovWiki\DbBundle\Service\MaxRankComputer
        arguments:
            - @doctrine.orm.entity_manager

    govwiki_db.importer.abstract:
        class: GovWiki\DbBundle\Importer\AbstractImporter
        arguments:
            - @database_connection
            - @govwiki_admin.manager.environment
        abstract: true

    govwiki_db.importer.government:
        class: GovWiki\DbBundle\Importer\GovernmentImporter
        arguments: [@carto_db.api]
        parent: govwiki_db.importer.abstract

    govwiki_db.importer.fin_data:
        class: GovWiki\DbBundle\Importer\FinDataImporter
        parent: govwiki_db.importer.abstract

    govwiki_db.manager.create_request:
        class: GovWiki\DbBundle\CreateRequest\CreateRequestManager
        arguments: [@doctrine.orm.default_entity_manager]
        
    translation.loader.db:
        class:     'GovWiki\DbBundle\Translation\DatabaseLoader'
        arguments:
            - @doctrine.orm.entity_manager
            - @govwiki_environment.current_environment
        tags:
            - { name: translation.loader, alias: db }

    govwiki_db.locale_listener:
        class: 'GovWiki\DbBundle\EventListener\LocaleListener'
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }