services:
    govwiki_db.service.max_ranks_computer:
        class: GovWiki\DbBundle\Service\MaxRankComputer
        arguments:
            - @doctrine.orm.entity_manager

    govwiki_db.importer.abstract:
        class: GovWiki\DbBundle\Importer\AbstractImporter
        arguments:
            - @database_connection
            - @govwiki_admin.manager.environment
        abstract: true

    govwiki_db.importer.government:
        class: GovWiki\DbBundle\Importer\GovernmentImporter
        arguments: [@carto_db.api]
        parent: govwiki_db.importer.abstract

    govwiki_db.form.type.alt_type:
        class: GovWiki\DbBundle\Form\Type\AltTypeType
        arguments: [@govwiki_admin.manager.environment]
        tags:
            - { name: form.type, alias: alt_type }

    govwiki_db.form.type.field_name:
        class: GovWiki\DbBundle\Form\Type\FieldNameType
        arguments: [@govwiki_admin.manager.environment]
        tags:
            - { name: form.type, alias: field_name }

    govwiki_db.form.type.color:
        class: GovWiki\DbBundle\Form\Type\ColorType
        tags:
            - { name: form.type, alias: color }

    govwiki_db.form.type.conditions_type:
        class: GovWiki\DbBundle\Form\Type\ConditionsType
        tags:
            - { name: form.type, alias: conditions }

    govwiki_db.form.type.colorized_county_condition:
        class: GovWiki\DbBundle\Form\Type\ColorizedCountyConditionType
        tags:
            - { name: form.type, alias: colorized_county_condition }

    govwiki_db.form.government:
        class: GovWiki\DbBundle\Form\GovernmentType
        arguments: [@govwiki_admin.manager.environment]
        tags:
            - { name: form.type, alias: government }

    govwiki_db.form.format:
        class: GovWiki\DbBundle\Form\FormatType
        arguments: [@govwiki_admin.manager.environment]
        tags:
            - { name: form.type, alias: format }