services:
    #
    # Wrapper under curl for easy access to CartoDB api.
    #
    carto_db.api:
        class: CartoDbBundle\Service\CartoDbApi
        arguments:
            - '' # Set by configuration parameter api_key
            - '' # Set by configuration parameter account_name