services:
    govwiki_environment.twig.extension:
        class: GovWiki\EnvironmentBundle\Twig\Extension
        arguments:
            - @govwiki_environment.manager
            - @translator
        tags:
            - { name: twig.extension }

    govwiki_environment.determinator.path:
        class: GovWiki\EnvironmentBundle\Determinator\PathDeterminator
        tags:
            - { name: environment.determinator, alias: path }

    govwiki_environment.determinator.host:
        class: GovWiki\EnvironmentBundle\Determinator\HostDeterminator
        arguments: [ @doctrine.orm.default_entity_manager ]
        tags:
            - { name: environment.determinator, alias: host }

    govwiki_environment.listener.determinator:
        class: GovWiki\EnvironmentBundle\EventListener\EnvironmentDeterminatorListener
        arguments:
            - '' # Set from configuration.
            - @govwiki_environment.storage
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    govwiki_environment.storage:
        class: GovWiki\EnvironmentBundle\Storage\EnvironmentStorage

    govwiki_environment.manager:
        class: GovWiki\EnvironmentBundle\Manager\EnvironmentManager
        arguments:
            - @doctrine.orm.default_entity_manager
            - @govwiki_environment.storage

    #
    # Use for read only access to current environment.
    #
    govwiki_environment.current_environment:
        class: GovWiki\DbBundle\Entity\Environment
        factory: [ @govwiki_environment.storage, get ]