services:
    govwiki_environment.twig.extension:
        class: GovWiki\EnvironmentBundle\Twig\Extension
        arguments:
            - @govwiki_environment.manager
            - @translator
        tags:
            - { name: twig.extension }

    govwiki_environment.determinator.path:
        class: GovWiki\EnvironmentBundle\Determinator\PathDeterminator
        tags:
            - { name: environment.determinator, alias: path }

    govwiki_environment.determinator.host:
        class: GovWiki\EnvironmentBundle\Determinator\HostDeterminator
        arguments: [ @doctrine.orm.default_entity_manager ]
        tags:
            - { name: environment.determinator, alias: host }

    govwiki_environment.listener.determinator:
        class: GovWiki\EnvironmentBundle\EventListener\EnvironmentDeterminatorListener
        arguments:
            - '' # Set from configuration.
            - @govwiki_environment.storage
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: -50 }

    govwiki_environment.storage:
        class: GovWiki\EnvironmentBundle\Storage\EnvironmentStorage

    govwiki_environment.data_manager.max_ranks:
        class: GovWiki\EnvironmentBundle\Manager\Data\MaxRank\MaxRankManager
        arguments: [ @doctrine.orm.default_entity_manager ]

    govwiki_environment.data_manager.government:
        class: GovWiki\EnvironmentBundle\Manager\Data\Government\GovernmentManager
        arguments: [ @doctrine.orm.default_entity_manager ]

    govwiki_environment.manager:
        class: GovWiki\EnvironmentBundle\Manager\Environment\EnvironmentManager
        arguments:
            - @doctrine.orm.default_entity_manager
            - @govwiki_environment.storage
            - @govwiki_environment.data_manager.government
            - @govwiki_environment.data_manager.max_ranks

    govwiki_environment.router:
        class: GovWiki\EnvironmentBundle\Router\RouterDecorator
        decorates: router
        arguments:
            - @govwiki_environment.router.inner
            - @govwiki_environment.storage
            - %determinator.name%